[package]
name = "Polymedia Profile"
version = "0.0.1"
authors = ["juzybits <https://twitter.com/juzybits>"]

[dependencies]
Sui = { local = "../../../sui/crates/sui-framework" }

[addresses]
polymedia_profile = "0x0"
